name: Unit Tests
on: [push]
jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install test dependencies
        run: npm install
      - name: Run unit tests 
        run: npm test
